_target_: exdark.models.exdarkdedicatedmodels.transformers.DetectionTransformer
transformers_checkpoint: SenseTime/deformable-detr
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  weight_decay: 0.0001
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [50 ]
  gamma: 0.1
lr_head: 0.0002
lr_backbone: 0.00002
freeze_backbone: false