defaults:
  - _self_
  - model: fasterrcnn

device: "cpu"

ckpt_path: null

visualize: true

threshold: 0.5
# placeholder for path
input: null

# placeholder for compatibility with train and eval
seed: null

hydra:
  run:
    dir: .
