# @package _global_

defaults:
  - _self_
  - model: fasterrcnn
  - datamodule: datamodule
  - trainer: trainer
  - logger: wandb
  - experiment: null

seed: 12345

device: "gpu"

hydra:
  run:
    dir: .


