method: grid
project: exdark
metric:
  name: val_mAP
  goal: maximize

program: exdark/modeling/train.py

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

parameters:
  model:
    values: [ "wrapperfasterrcnn", "wrapperretinanet", "wrapperfcos" ]
  datamodule:
    values: [ "datamodule", "hvicid", "gamma" ]
