method: grid
project: exdark
metric:
  name: val_mAP
  goal: maximize

program: exdark/modeling/train.py

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

parameters:
  model:
    values: [ "def_detr" ]
  datamodule:
    values: [ "glare", "datamodule", "hvicid", "gamma",  ]
  trainer.max_epochs:
    values: [ 50 ]
