method: grid
project: exdark
metric:
  name: val_mAP
  goal: maximize

program: exdark/modeling/train.py

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

parameters:
  model:
    values: [ "fasterrcnn", "retinanet", "fcos", "def_detr" ]
  model.freeze_backbone:
    values: [ false, true ]
